[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.0.1"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.70"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.31.0"